### ISSUE TITLE
Some Suggestion 

### ISSUE THREAD

**Issue by splimter** [khalilrume/notes-app#1]
interface class name should be capitalized:
https://github.com/khalilrume/notes-app/blob/22526166d27c01d194afb14ab9e79c4b7fe6d874/sripte.ts#L14

set a better naming as deleteelm didn't make sense to me, and also use camelCase writing 
https://github.com/khalilrume/notes-app/blob/22526166d27c01d194afb14ab9e79c4b7fe6d874/sripte.ts#L57

**Comment by ahmedkhalilexe** [comment]
done fixed.
